include:
  - project: 'ihp/julia/julia-gitlab-ci-templates'
    ref: v1.2.0
    file: '/templates.gitlab-ci.yaml'

test:
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.0", "1.3", "1.6", "1.7"]
  variables:
    CI_JULIA_TEST_THREADS: THREADS_OFF
  extends:
    - .julia.setup
    - .julia.test
